//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQS.Security
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string EmailAddressField;
        
        private string FullNameField;
        
        private bool IsDisabledField;
        
        private bool IsSubvendorManagerField;
        
        private string LTEmailAddressField;
        
        private string LTFullNameField;
        
        private string LTUsernameField;
        
        private string LanguagePairsField;
        
        private byte MergeTypeField;
        
        private string MobilePhoneNumberField;
        
        private MQS.Security.UserPackageWorkflowType PackageWorkflowTypeField;
        
        private string PasswordField;
        
        private string PhoneNumberField;
        
        private System.Nullable<System.Guid> SecondarySIDField;
        
        private System.Guid UserGuidField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDisabled
        {
            get
            {
                return this.IsDisabledField;
            }
            set
            {
                this.IsDisabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSubvendorManager
        {
            get
            {
                return this.IsSubvendorManagerField;
            }
            set
            {
                this.IsSubvendorManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LTEmailAddress
        {
            get
            {
                return this.LTEmailAddressField;
            }
            set
            {
                this.LTEmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LTFullName
        {
            get
            {
                return this.LTFullNameField;
            }
            set
            {
                this.LTFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LTUsername
        {
            get
            {
                return this.LTUsernameField;
            }
            set
            {
                this.LTUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguagePairs
        {
            get
            {
                return this.LanguagePairsField;
            }
            set
            {
                this.LanguagePairsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte MergeType
        {
            get
            {
                return this.MergeTypeField;
            }
            set
            {
                this.MergeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNumber
        {
            get
            {
                return this.MobilePhoneNumberField;
            }
            set
            {
                this.MobilePhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.Security.UserPackageWorkflowType PackageWorkflowType
        {
            get
            {
                return this.PackageWorkflowTypeField;
            }
            set
            {
                this.PackageWorkflowTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SecondarySID
        {
            get
            {
                return this.SecondarySIDField;
            }
            set
            {
                this.SecondarySIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPackageWorkflowType", Namespace="http://schemas.datacontract.org/2004/07/MemoQServices")]
    public enum UserPackageWorkflowType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PackagesOnly = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class GroupInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.Guid GroupGuidField;
        
        private string GroupNameField;
        
        private bool IsDisabledField;
        
        private bool IsSubvendorGroupField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GroupGuid
        {
            get
            {
                return this.GroupGuidField;
            }
            set
            {
                this.GroupGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDisabled
        {
            get
            {
                return this.IsDisabledField;
            }
            set
            {
                this.IsDisabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSubvendorGroup
        {
            get
            {
                return this.IsSubvendorGroupField;
            }
            set
            {
                this.IsSubvendorGroupField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectPermission", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class ObjectPermission : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ExpirationDateField;
        
        private System.Guid GuidOfUserOrGroupField;
        
        private int PermissionIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GuidOfUserOrGroup
        {
            get
            {
                return this.GuidOfUserOrGroupField;
            }
            set
            {
                this.GuidOfUserOrGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PermissionId
        {
            get
            {
                return this.PermissionIdField;
            }
            set
            {
                this.PermissionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnexpectedFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class UnexpectedFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class GenericFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kilgray.com/memoqservices/2007", ConfigurationName="MQS.Security.ISecurityService")]
    public interface ISecurityService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsers", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersUnexpectedFaultFa" +
            "ult", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersGenericFaultFault" +
            "", Name="GenericFault")]
        MQS.Security.UserInfo[] ListUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsers", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersResponse")]
        System.Threading.Tasks.Task<MQS.Security.UserInfo[]> ListUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorManagers", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorManagersRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorManagersUnexp" +
            "ectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorManagersGener" +
            "icFaultFault", Name="GenericFault")]
        MQS.Security.UserInfo[] ListSubvendorManagers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorManagers", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorManagersRespo" +
            "nse")]
        System.Threading.Tasks.Task<MQS.Security.UserInfo[]> ListSubvendorManagersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/GetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetUserUnexpectedFaultFaul" +
            "t", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetUserGenericFaultFault", Name="GenericFault")]
        MQS.Security.UserInfo GetUser(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/GetUserResponse")]
        System.Threading.Tasks.Task<MQS.Security.UserInfo> GetUserAsync(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/CreateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateUserUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateUserGenericFaultFaul" +
            "t", Name="GenericFault")]
        System.Guid CreateUser(MQS.Security.UserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/CreateUserResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateUserAsync(MQS.Security.UserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateUserUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateUserGenericFaultFaul" +
            "t", Name="GenericFault")]
        void UpdateUser(MQS.Security.UserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(MQS.Security.UserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteUserUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteUserGenericFaultFaul" +
            "t", Name="GenericFault")]
        void DeleteUser(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsOfUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsOfUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsOfUserUnexpected" +
            "FaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsOfUserGenericFau" +
            "ltFault", Name="GenericFault")]
        MQS.Security.GroupInfo[] ListGroupsOfUser(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsOfUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsOfUserResponse")]
        System.Threading.Tasks.Task<MQS.Security.GroupInfo[]> ListGroupsOfUserAsync(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetGroupsOfUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/SetGroupsOfUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetGroupsOfUserUnexpectedF" +
            "aultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetGroupsOfUserGenericFaul" +
            "tFault", Name="GenericFault")]
        void SetGroupsOfUser(System.Guid userGuid, System.Guid[] groupGuids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetGroupsOfUser", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/SetGroupsOfUserResponse")]
        System.Threading.Tasks.Task SetGroupsOfUserAsync(System.Guid userGuid, System.Guid[] groupGuids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/AddSubvendorManagerToGroup" +
            "", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/AddSubvendorManagerToGroup" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/AddSubvendorManagerToGroup" +
            "UnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/AddSubvendorManagerToGroup" +
            "GenericFaultFault", Name="GenericFault")]
        void AddSubvendorManagerToGroup(System.Guid userGuid, System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/AddSubvendorManagerToGroup" +
            "", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/AddSubvendorManagerToGroup" +
            "Response")]
        System.Threading.Tasks.Task AddSubvendorManagerToGroupAsync(System.Guid userGuid, System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/RemoveSubvendorManagerFrom" +
            "Group", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/RemoveSubvendorManagerFrom" +
            "GroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/RemoveSubvendorManagerFrom" +
            "GroupUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/RemoveSubvendorManagerFrom" +
            "GroupGenericFaultFault", Name="GenericFault")]
        void RemoveSubvendorManagerFromGroup(System.Guid userGuid, System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/RemoveSubvendorManagerFrom" +
            "Group", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/RemoveSubvendorManagerFrom" +
            "GroupResponse")]
        System.Threading.Tasks.Task RemoveSubvendorManagerFromGroupAsync(System.Guid userGuid, System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroups", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsGenericFaultFaul" +
            "t", Name="GenericFault")]
        MQS.Security.GroupInfo[] ListGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroups", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListGroupsResponse")]
        System.Threading.Tasks.Task<MQS.Security.GroupInfo[]> ListGroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorGroups", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorGroupsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorGroupsUnexpec" +
            "tedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorGroupsGeneric" +
            "FaultFault", Name="GenericFault")]
        MQS.Security.GroupInfo[] ListSubvendorGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorGroups", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListSubvendorGroupsRespons" +
            "e")]
        System.Threading.Tasks.Task<MQS.Security.GroupInfo[]> ListSubvendorGroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/GetGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetGroupUnexpectedFaultFau" +
            "lt", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetGroupGenericFaultFault", Name="GenericFault")]
        MQS.Security.GroupInfo GetGroup(System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/GetGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/GetGroupResponse")]
        System.Threading.Tasks.Task<MQS.Security.GroupInfo> GetGroupAsync(System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/CreateGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateGroupUnexpectedFault" +
            "Fault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateGroupGenericFaultFau" +
            "lt", Name="GenericFault")]
        System.Guid CreateGroup(MQS.Security.GroupInfo groupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/CreateGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/CreateGroupResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateGroupAsync(MQS.Security.GroupInfo groupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateGroupUnexpectedFault" +
            "Fault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateGroupGenericFaultFau" +
            "lt", Name="GenericFault")]
        void UpdateGroup(MQS.Security.GroupInfo groupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/UpdateGroupResponse")]
        System.Threading.Tasks.Task UpdateGroupAsync(MQS.Security.GroupInfo groupInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteGroupUnexpectedFault" +
            "Fault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteGroupGenericFaultFau" +
            "lt", Name="GenericFault")]
        void DeleteGroup(System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/DeleteGroupResponse")]
        System.Threading.Tasks.Task DeleteGroupAsync(System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersOfGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersOfGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersOfGroupUnexpected" +
            "FaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersOfGroupGenericFau" +
            "ltFault", Name="GenericFault")]
        MQS.Security.UserInfo[] ListUsersOfGroup(System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersOfGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListUsersOfGroupResponse")]
        System.Threading.Tasks.Task<MQS.Security.UserInfo[]> ListUsersOfGroupAsync(System.Guid groupGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetUsersOfGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/SetUsersOfGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetUsersOfGroupUnexpectedF" +
            "aultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetUsersOfGroupGenericFaul" +
            "tFault", Name="GenericFault")]
        void SetUsersOfGroup(System.Guid groupGuid, System.Guid[] userGuids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetUsersOfGroup", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/SetUsersOfGroupResponse")]
        System.Threading.Tasks.Task SetUsersOfGroupAsync(System.Guid groupGuid, System.Guid[] userGuids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetObjectPermissions", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/SetObjectPermissionsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetObjectPermissionsUnexpe" +
            "ctedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetObjectPermissionsGeneri" +
            "cFaultFault", Name="GenericFault")]
        void SetObjectPermissions(System.Guid objectGuid, MQS.Security.ObjectPermission[] permissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/SetObjectPermissions", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/SetObjectPermissionsRespon" +
            "se")]
        System.Threading.Tasks.Task SetObjectPermissionsAsync(System.Guid objectGuid, MQS.Security.ObjectPermission[] permissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListObjectPermissions", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListObjectPermissionsRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListObjectPermissionsUnexp" +
            "ectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListObjectPermissionsGener" +
            "icFaultFault", Name="GenericFault")]
        MQS.Security.ObjectPermission[] ListObjectPermissions(System.Guid objectGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/ListObjectPermissions", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/ListObjectPermissionsRespo" +
            "nse")]
        System.Threading.Tasks.Task<MQS.Security.ObjectPermission[]> ListObjectPermissionsAsync(System.Guid objectGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/Login", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/LoginUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/LoginGenericFaultFault", Name="GenericFault")]
        string Login(string userName, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/Login", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string userName, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/Logout", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/LogoutUnexpectedFaultFault" +
            "", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.Security.GenericFault), Action="http://kilgray.com/memoqservices/2007/ISecurityService/LogoutGenericFaultFault", Name="GenericFault")]
        void Logout(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ISecurityService/Logout", ReplyAction="http://kilgray.com/memoqservices/2007/ISecurityService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string sessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : MQS.Security.ISecurityService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<MQS.Security.ISecurityService>, MQS.Security.ISecurityService
    {
        
        public SecurityServiceClient()
        {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MQS.Security.UserInfo[] ListUsers()
        {
            return base.Channel.ListUsers();
        }
        
        public System.Threading.Tasks.Task<MQS.Security.UserInfo[]> ListUsersAsync()
        {
            return base.Channel.ListUsersAsync();
        }
        
        public MQS.Security.UserInfo[] ListSubvendorManagers()
        {
            return base.Channel.ListSubvendorManagers();
        }
        
        public System.Threading.Tasks.Task<MQS.Security.UserInfo[]> ListSubvendorManagersAsync()
        {
            return base.Channel.ListSubvendorManagersAsync();
        }
        
        public MQS.Security.UserInfo GetUser(System.Guid userGuid)
        {
            return base.Channel.GetUser(userGuid);
        }
        
        public System.Threading.Tasks.Task<MQS.Security.UserInfo> GetUserAsync(System.Guid userGuid)
        {
            return base.Channel.GetUserAsync(userGuid);
        }
        
        public System.Guid CreateUser(MQS.Security.UserInfo userInfo)
        {
            return base.Channel.CreateUser(userInfo);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateUserAsync(MQS.Security.UserInfo userInfo)
        {
            return base.Channel.CreateUserAsync(userInfo);
        }
        
        public void UpdateUser(MQS.Security.UserInfo userInfo)
        {
            base.Channel.UpdateUser(userInfo);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(MQS.Security.UserInfo userInfo)
        {
            return base.Channel.UpdateUserAsync(userInfo);
        }
        
        public void DeleteUser(System.Guid userGuid)
        {
            base.Channel.DeleteUser(userGuid);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(System.Guid userGuid)
        {
            return base.Channel.DeleteUserAsync(userGuid);
        }
        
        public MQS.Security.GroupInfo[] ListGroupsOfUser(System.Guid userGuid)
        {
            return base.Channel.ListGroupsOfUser(userGuid);
        }
        
        public System.Threading.Tasks.Task<MQS.Security.GroupInfo[]> ListGroupsOfUserAsync(System.Guid userGuid)
        {
            return base.Channel.ListGroupsOfUserAsync(userGuid);
        }
        
        public void SetGroupsOfUser(System.Guid userGuid, System.Guid[] groupGuids)
        {
            base.Channel.SetGroupsOfUser(userGuid, groupGuids);
        }
        
        public System.Threading.Tasks.Task SetGroupsOfUserAsync(System.Guid userGuid, System.Guid[] groupGuids)
        {
            return base.Channel.SetGroupsOfUserAsync(userGuid, groupGuids);
        }
        
        public void AddSubvendorManagerToGroup(System.Guid userGuid, System.Guid groupGuid)
        {
            base.Channel.AddSubvendorManagerToGroup(userGuid, groupGuid);
        }
        
        public System.Threading.Tasks.Task AddSubvendorManagerToGroupAsync(System.Guid userGuid, System.Guid groupGuid)
        {
            return base.Channel.AddSubvendorManagerToGroupAsync(userGuid, groupGuid);
        }
        
        public void RemoveSubvendorManagerFromGroup(System.Guid userGuid, System.Guid groupGuid)
        {
            base.Channel.RemoveSubvendorManagerFromGroup(userGuid, groupGuid);
        }
        
        public System.Threading.Tasks.Task RemoveSubvendorManagerFromGroupAsync(System.Guid userGuid, System.Guid groupGuid)
        {
            return base.Channel.RemoveSubvendorManagerFromGroupAsync(userGuid, groupGuid);
        }
        
        public MQS.Security.GroupInfo[] ListGroups()
        {
            return base.Channel.ListGroups();
        }
        
        public System.Threading.Tasks.Task<MQS.Security.GroupInfo[]> ListGroupsAsync()
        {
            return base.Channel.ListGroupsAsync();
        }
        
        public MQS.Security.GroupInfo[] ListSubvendorGroups()
        {
            return base.Channel.ListSubvendorGroups();
        }
        
        public System.Threading.Tasks.Task<MQS.Security.GroupInfo[]> ListSubvendorGroupsAsync()
        {
            return base.Channel.ListSubvendorGroupsAsync();
        }
        
        public MQS.Security.GroupInfo GetGroup(System.Guid groupGuid)
        {
            return base.Channel.GetGroup(groupGuid);
        }
        
        public System.Threading.Tasks.Task<MQS.Security.GroupInfo> GetGroupAsync(System.Guid groupGuid)
        {
            return base.Channel.GetGroupAsync(groupGuid);
        }
        
        public System.Guid CreateGroup(MQS.Security.GroupInfo groupInfo)
        {
            return base.Channel.CreateGroup(groupInfo);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateGroupAsync(MQS.Security.GroupInfo groupInfo)
        {
            return base.Channel.CreateGroupAsync(groupInfo);
        }
        
        public void UpdateGroup(MQS.Security.GroupInfo groupInfo)
        {
            base.Channel.UpdateGroup(groupInfo);
        }
        
        public System.Threading.Tasks.Task UpdateGroupAsync(MQS.Security.GroupInfo groupInfo)
        {
            return base.Channel.UpdateGroupAsync(groupInfo);
        }
        
        public void DeleteGroup(System.Guid groupGuid)
        {
            base.Channel.DeleteGroup(groupGuid);
        }
        
        public System.Threading.Tasks.Task DeleteGroupAsync(System.Guid groupGuid)
        {
            return base.Channel.DeleteGroupAsync(groupGuid);
        }
        
        public MQS.Security.UserInfo[] ListUsersOfGroup(System.Guid groupGuid)
        {
            return base.Channel.ListUsersOfGroup(groupGuid);
        }
        
        public System.Threading.Tasks.Task<MQS.Security.UserInfo[]> ListUsersOfGroupAsync(System.Guid groupGuid)
        {
            return base.Channel.ListUsersOfGroupAsync(groupGuid);
        }
        
        public void SetUsersOfGroup(System.Guid groupGuid, System.Guid[] userGuids)
        {
            base.Channel.SetUsersOfGroup(groupGuid, userGuids);
        }
        
        public System.Threading.Tasks.Task SetUsersOfGroupAsync(System.Guid groupGuid, System.Guid[] userGuids)
        {
            return base.Channel.SetUsersOfGroupAsync(groupGuid, userGuids);
        }
        
        public void SetObjectPermissions(System.Guid objectGuid, MQS.Security.ObjectPermission[] permissions)
        {
            base.Channel.SetObjectPermissions(objectGuid, permissions);
        }
        
        public System.Threading.Tasks.Task SetObjectPermissionsAsync(System.Guid objectGuid, MQS.Security.ObjectPermission[] permissions)
        {
            return base.Channel.SetObjectPermissionsAsync(objectGuid, permissions);
        }
        
        public MQS.Security.ObjectPermission[] ListObjectPermissions(System.Guid objectGuid)
        {
            return base.Channel.ListObjectPermissions(objectGuid);
        }
        
        public System.Threading.Tasks.Task<MQS.Security.ObjectPermission[]> ListObjectPermissionsAsync(System.Guid objectGuid)
        {
            return base.Channel.ListObjectPermissionsAsync(objectGuid);
        }
        
        public string Login(string userName, string passwordHash)
        {
            return base.Channel.Login(userName, passwordHash);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string userName, string passwordHash)
        {
            return base.Channel.LoginAsync(userName, passwordHash);
        }
        
        public void Logout(string sessionId)
        {
            base.Channel.Logout(sessionId);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string sessionId)
        {
            return base.Channel.LogoutAsync(sessionId);
        }
    }
}
