//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQS.TB
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TB.HeavyResourceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TB.TBInfo))]
    public partial class ResourceInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.Guid GuidField;
        
        private string NameField;
        
        private bool ReadonlyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Readonly
        {
            get
            {
                return this.ReadonlyField;
            }
            set
            {
                this.ReadonlyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeavyResourceInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TB.TBInfo))]
    public partial class HeavyResourceInfo : MQS.TB.ResourceInfo
    {
        
        private string ClientField;
        
        private string DomainField;
        
        private string ProjectField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TBInfo : MQS.TB.HeavyResourceInfo
    {
        
        private bool IsModeratedField;
        
        private string[] LanguageCodesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsModerated
        {
            get
            {
                return this.IsModeratedField;
            }
            set
            {
                this.IsModeratedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LanguageCodes
        {
            get
            {
                return this.LanguageCodesField;
            }
            set
            {
                this.LanguageCodesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBFilter", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TBFilter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MQS.TB.TBFilterLangMode LangModeField;
        
        private string[] LanguageCodesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TB.TBFilterLangMode LangMode
        {
            get
            {
                return this.LangModeField;
            }
            set
            {
                this.LangModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LanguageCodes
        {
            get
            {
                return this.LanguageCodesField;
            }
            set
            {
                this.LanguageCodesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBFilterLangMode", Namespace="http://kilgray.com/memoqservices/2007")]
    public enum TBFilterLangMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnyMatch = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllMatch = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceUpdateInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TB.HeavyResourceUpdateInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TB.TBUpdateInfo))]
    public partial class ResourceUpdateInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.Guid GuidField;
        
        private string NameField;
        
        private bool ReadonlyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Readonly
        {
            get
            {
                return this.ReadonlyField;
            }
            set
            {
                this.ReadonlyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeavyResourceUpdateInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TB.TBUpdateInfo))]
    public partial class HeavyResourceUpdateInfo : MQS.TB.ResourceUpdateInfo
    {
        
        private string ClientField;
        
        private string DomainField;
        
        private string ProjectField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBUpdateInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TBUpdateInfo : MQS.TB.HeavyResourceUpdateInfo
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSVImportResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class CSVImportResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AllCountField;
        
        private int SuccessCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllCount
        {
            get
            {
                return this.AllCountField;
            }
            set
            {
                this.AllCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuccessCount
        {
            get
            {
                return this.SuccessCountField;
            }
            set
            {
                this.SuccessCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnexpectedFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class UnexpectedFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class GenericFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kilgray.com/memoqservices/2007", ConfigurationName="MQS.TB.ITBService")]
    public interface ITBService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/CreateAndPublish", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/CreateAndPublishResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/CreateAndPublishUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/CreateAndPublishGenericFaultFaul" +
            "t", Name="GenericFault")]
        System.Guid CreateAndPublish(MQS.TB.TBInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/CreateAndPublish", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/CreateAndPublishResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateAndPublishAsync(MQS.TB.TBInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBs", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/ListTBsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBsUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBsGenericFaultFault", Name="GenericFault")]
        MQS.TB.TBInfo[] ListTBs(string[] languages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBs", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/ListTBsResponse")]
        System.Threading.Tasks.Task<MQS.TB.TBInfo[]> ListTBsAsync(string[] languages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBs2", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/ListTBs2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBs2UnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBs2GenericFaultFault", Name="GenericFault")]
        MQS.TB.TBInfo[] ListTBs2(MQS.TB.TBFilter tbFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/ListTBs2", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/ListTBs2Response")]
        System.Threading.Tasks.Task<MQS.TB.TBInfo[]> ListTBs2Async(MQS.TB.TBFilter tbFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/GetTBInfo", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/GetTBInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/GetTBInfoUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/GetTBInfoGenericFaultFault", Name="GenericFault")]
        MQS.TB.TBInfo GetTBInfo(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/GetTBInfo", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/GetTBInfoResponse")]
        System.Threading.Tasks.Task<MQS.TB.TBInfo> GetTBInfoAsync(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/UpdateProperties", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/UpdatePropertiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/UpdatePropertiesUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/UpdatePropertiesGenericFaultFaul" +
            "t", Name="GenericFault")]
        void UpdateProperties(MQS.TB.TBUpdateInfo updateInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/UpdateProperties", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/UpdatePropertiesResponse")]
        System.Threading.Tasks.Task UpdatePropertiesAsync(MQS.TB.TBUpdateInfo updateInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/DeleteTB", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/DeleteTBResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/DeleteTBUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/DeleteTBGenericFaultFault", Name="GenericFault")]
        void DeleteTB(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/DeleteTB", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/DeleteTBResponse")]
        System.Threading.Tasks.Task DeleteTBAsync(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/ConvertToQTerm", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/ConvertToQTermResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/ConvertToQTermUnexpectedFaultFau" +
            "lt", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/ConvertToQTermGenericFaultFault", Name="GenericFault")]
        void ConvertToQTerm(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/ConvertToQTerm", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/ConvertToQTermResponse")]
        System.Threading.Tasks.Task ConvertToQTermAsync(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVImportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVImportUnexpectedF" +
            "aultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVImportGenericFaul" +
            "tFault", Name="GenericFault")]
        System.Guid BeginChunkedCSVImport(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVImportResponse")]
        System.Threading.Tasks.Task<System.Guid> BeginChunkedCSVImportAsync(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/AddNextCSVChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/AddNextCSVChunkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/AddNextCSVChunkUnexpectedFaultFa" +
            "ult", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/AddNextCSVChunkGenericFaultFault" +
            "", Name="GenericFault")]
        void AddNextCSVChunk(System.Guid sessionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/AddNextCSVChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/AddNextCSVChunkResponse")]
        System.Threading.Tasks.Task AddNextCSVChunkAsync(System.Guid sessionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVImportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVImportUnexpectedFau" +
            "ltFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVImportGenericFaultF" +
            "ault", Name="GenericFault")]
        MQS.TB.CSVImportResult EndChunkedCSVImport(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVImportResponse")]
        System.Threading.Tasks.Task<MQS.TB.CSVImportResult> EndChunkedCSVImportAsync(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVExportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVExportUnexpectedF" +
            "aultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVExportGenericFaul" +
            "tFault", Name="GenericFault")]
        System.Guid BeginChunkedCSVExport(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedCSVExportResponse")]
        System.Threading.Tasks.Task<System.Guid> BeginChunkedCSVExportAsync(System.Guid tbGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedMultiTermExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedMultiTermExportRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedMultiTermExportUnexp" +
            "ectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedMultiTermExportGener" +
            "icFaultFault", Name="GenericFault")]
        MQS.TB.BeginChunkedMultiTermExportResponse BeginChunkedMultiTermExport(MQS.TB.BeginChunkedMultiTermExportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedMultiTermExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/BeginChunkedMultiTermExportRespo" +
            "nse")]
        System.Threading.Tasks.Task<MQS.TB.BeginChunkedMultiTermExportResponse> BeginChunkedMultiTermExportAsync(MQS.TB.BeginChunkedMultiTermExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextExportChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/GetNextExportChunkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextExportChunkUnexpectedFaul" +
            "tFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextExportChunkGenericFaultFa" +
            "ult", Name="GenericFault")]
        byte[] GetNextExportChunk(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextExportChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/GetNextExportChunkResponse")]
        System.Threading.Tasks.Task<byte[]> GetNextExportChunkAsync(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedExportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedExportUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedExportGenericFaultFaul" +
            "t", Name="GenericFault")]
        void EndChunkedExport(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedExportResponse")]
        System.Threading.Tasks.Task EndChunkedExportAsync(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextCSVChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/GetNextCSVChunkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextCSVChunkUnexpectedFaultFa" +
            "ult", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextCSVChunkGenericFaultFault" +
            "", Name="GenericFault")]
        byte[] GetNextCSVChunk(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/GetNextCSVChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/GetNextCSVChunkResponse")]
        System.Threading.Tasks.Task<byte[]> GetNextCSVChunkAsync(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVExportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVExportUnexpectedFau" +
            "ltFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TB.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVExportGenericFaultF" +
            "ault", Name="GenericFault")]
        void EndChunkedCSVExport(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITBService/EndChunkedCSVExportResponse")]
        System.Threading.Tasks.Task EndChunkedCSVExportAsync(System.Guid sessionId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginChunkedMultiTermExport", WrapperNamespace="http://kilgray.com/memoqservices/2007", IsWrapped=true)]
    public partial class BeginChunkedMultiTermExportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kilgray.com/memoqservices/2007", Order=0)]
        public System.Guid tbGuid;
        
        public BeginChunkedMultiTermExportRequest()
        {
        }
        
        public BeginChunkedMultiTermExportRequest(System.Guid tbGuid)
        {
            this.tbGuid = tbGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginChunkedMultiTermExportResponse", WrapperNamespace="http://kilgray.com/memoqservices/2007", IsWrapped=true)]
    public partial class BeginChunkedMultiTermExportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kilgray.com/memoqservices/2007", Order=0)]
        public System.Guid BeginChunkedMultiTermExportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kilgray.com/memoqservices/2007", Order=1)]
        public string xdt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kilgray.com/memoqservices/2007", Order=2)]
        public string xdl;
        
        public BeginChunkedMultiTermExportResponse()
        {
        }
        
        public BeginChunkedMultiTermExportResponse(System.Guid BeginChunkedMultiTermExportResult, string xdt, string xdl)
        {
            this.BeginChunkedMultiTermExportResult = BeginChunkedMultiTermExportResult;
            this.xdt = xdt;
            this.xdl = xdl;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITBServiceChannel : MQS.TB.ITBService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TBServiceClient : System.ServiceModel.ClientBase<MQS.TB.ITBService>, MQS.TB.ITBService
    {
        
        public TBServiceClient()
        {
        }
        
        public TBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Guid CreateAndPublish(MQS.TB.TBInfo info)
        {
            return base.Channel.CreateAndPublish(info);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateAndPublishAsync(MQS.TB.TBInfo info)
        {
            return base.Channel.CreateAndPublishAsync(info);
        }
        
        public MQS.TB.TBInfo[] ListTBs(string[] languages)
        {
            return base.Channel.ListTBs(languages);
        }
        
        public System.Threading.Tasks.Task<MQS.TB.TBInfo[]> ListTBsAsync(string[] languages)
        {
            return base.Channel.ListTBsAsync(languages);
        }
        
        public MQS.TB.TBInfo[] ListTBs2(MQS.TB.TBFilter tbFilter)
        {
            return base.Channel.ListTBs2(tbFilter);
        }
        
        public System.Threading.Tasks.Task<MQS.TB.TBInfo[]> ListTBs2Async(MQS.TB.TBFilter tbFilter)
        {
            return base.Channel.ListTBs2Async(tbFilter);
        }
        
        public MQS.TB.TBInfo GetTBInfo(System.Guid tbGuid)
        {
            return base.Channel.GetTBInfo(tbGuid);
        }
        
        public System.Threading.Tasks.Task<MQS.TB.TBInfo> GetTBInfoAsync(System.Guid tbGuid)
        {
            return base.Channel.GetTBInfoAsync(tbGuid);
        }
        
        public void UpdateProperties(MQS.TB.TBUpdateInfo updateInfo)
        {
            base.Channel.UpdateProperties(updateInfo);
        }
        
        public System.Threading.Tasks.Task UpdatePropertiesAsync(MQS.TB.TBUpdateInfo updateInfo)
        {
            return base.Channel.UpdatePropertiesAsync(updateInfo);
        }
        
        public void DeleteTB(System.Guid tbGuid)
        {
            base.Channel.DeleteTB(tbGuid);
        }
        
        public System.Threading.Tasks.Task DeleteTBAsync(System.Guid tbGuid)
        {
            return base.Channel.DeleteTBAsync(tbGuid);
        }
        
        public void ConvertToQTerm(System.Guid tbGuid)
        {
            base.Channel.ConvertToQTerm(tbGuid);
        }
        
        public System.Threading.Tasks.Task ConvertToQTermAsync(System.Guid tbGuid)
        {
            return base.Channel.ConvertToQTermAsync(tbGuid);
        }
        
        public System.Guid BeginChunkedCSVImport(System.Guid tbGuid)
        {
            return base.Channel.BeginChunkedCSVImport(tbGuid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> BeginChunkedCSVImportAsync(System.Guid tbGuid)
        {
            return base.Channel.BeginChunkedCSVImportAsync(tbGuid);
        }
        
        public void AddNextCSVChunk(System.Guid sessionId, byte[] data)
        {
            base.Channel.AddNextCSVChunk(sessionId, data);
        }
        
        public System.Threading.Tasks.Task AddNextCSVChunkAsync(System.Guid sessionId, byte[] data)
        {
            return base.Channel.AddNextCSVChunkAsync(sessionId, data);
        }
        
        public MQS.TB.CSVImportResult EndChunkedCSVImport(System.Guid sessionId)
        {
            return base.Channel.EndChunkedCSVImport(sessionId);
        }
        
        public System.Threading.Tasks.Task<MQS.TB.CSVImportResult> EndChunkedCSVImportAsync(System.Guid sessionId)
        {
            return base.Channel.EndChunkedCSVImportAsync(sessionId);
        }
        
        public System.Guid BeginChunkedCSVExport(System.Guid tbGuid)
        {
            return base.Channel.BeginChunkedCSVExport(tbGuid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> BeginChunkedCSVExportAsync(System.Guid tbGuid)
        {
            return base.Channel.BeginChunkedCSVExportAsync(tbGuid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MQS.TB.BeginChunkedMultiTermExportResponse MQS.TB.ITBService.BeginChunkedMultiTermExport(MQS.TB.BeginChunkedMultiTermExportRequest request)
        {
            return base.Channel.BeginChunkedMultiTermExport(request);
        }
        
        public System.Guid BeginChunkedMultiTermExport(System.Guid tbGuid, out string xdt, out string xdl)
        {
            MQS.TB.BeginChunkedMultiTermExportRequest inValue = new MQS.TB.BeginChunkedMultiTermExportRequest();
            inValue.tbGuid = tbGuid;
            MQS.TB.BeginChunkedMultiTermExportResponse retVal = ((MQS.TB.ITBService)(this)).BeginChunkedMultiTermExport(inValue);
            xdt = retVal.xdt;
            xdl = retVal.xdl;
            return retVal.BeginChunkedMultiTermExportResult;
        }
        
        public System.Threading.Tasks.Task<MQS.TB.BeginChunkedMultiTermExportResponse> BeginChunkedMultiTermExportAsync(MQS.TB.BeginChunkedMultiTermExportRequest request)
        {
            return base.Channel.BeginChunkedMultiTermExportAsync(request);
        }
        
        public byte[] GetNextExportChunk(System.Guid sessionId)
        {
            return base.Channel.GetNextExportChunk(sessionId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetNextExportChunkAsync(System.Guid sessionId)
        {
            return base.Channel.GetNextExportChunkAsync(sessionId);
        }
        
        public void EndChunkedExport(System.Guid sessionId)
        {
            base.Channel.EndChunkedExport(sessionId);
        }
        
        public System.Threading.Tasks.Task EndChunkedExportAsync(System.Guid sessionId)
        {
            return base.Channel.EndChunkedExportAsync(sessionId);
        }
        
        public byte[] GetNextCSVChunk(System.Guid sessionId)
        {
            return base.Channel.GetNextCSVChunk(sessionId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetNextCSVChunkAsync(System.Guid sessionId)
        {
            return base.Channel.GetNextCSVChunkAsync(sessionId);
        }
        
        public void EndChunkedCSVExport(System.Guid sessionId)
        {
            base.Channel.EndChunkedCSVExport(sessionId);
        }
        
        public System.Threading.Tasks.Task EndChunkedCSVExportAsync(System.Guid sessionId)
        {
            return base.Channel.EndChunkedCSVExportAsync(sessionId);
        }
    }
}
